### ISSUE TITLE
full Smarty 3 compatibility

### ISSUE THREAD

**Issue by JonisoftGermany** [JonisoftGermany/SmartyML#2]
A new class for full Smarty 3 compatibility. There are some changes in some functions.

**Comment by binalpandya** [comment]
Hi JonisoftGermany  , can you please help me with this?

**Comment by binalpandya** [comment]
I need SMARTYML Class for SMARTy3

**Comment by JonisoftGermany** [comment]
Hi binalpandya,
I worked on a Smarty 3 Version of SmartyML last year and I used it in two projects. In the beginning I had some problems with the new object model, but I coded some work arounds. The code is not very beautiful but the code works.
http://downloads.jonisoft.de/smartyml3.txt
The SmartyML-Class is just an extension of the original Smarty-Class. You can use it like the original software. In the $languages-Array you define the available languages for your project. For each language you need an translation-file. The location of the folder with the files can be defined in the global var $smarty_lang_dir. Another global definition is the default language: $smarty_lang_default. You can define these two informations in a global config file in your project.
When you create a new SmartyML-Object (you need only one per lifetime, like Smarty), you can tell the object which language you want to use:
$gui = new SmartyML(); // creates new Layout with default language
$gui = new SmartyML('en'); // creates new Layout in English
I hope this helps you a bit.
Jonathan

**Comment by binalpandya** [comment]
Hi Jonathan,
Thank you so much,
This helps me a lot!!
can you give me text file?how it will know that language varible is passed in tpl file??

**Comment by JonisoftGermany** [comment]
In the folder 'locales'* I use the following file names for the language files:
en.txt for English
de.txt for German
...
etc.

In each file you should define the same placeholders, like:
booking_placeholder=Buchung
bookings_placeholder=Buchen Sie jetzt hier
// comment row
portal_name=Buchungsportal

Empty rows and rows beginning with a double slash // will be ignored
On the left side there is the name of the placeholder. It will be replaced by the right side of the =.

* You can name it however you want.

**Comment by binalpandya** [comment]
Hi,

Do you have library for SmartyPaginate
<http://www.phpinsider.com/php/code/SmartyPaginate/> in smarty 3??

Regards, Binal

**Comment by binalpandya** [comment]
HI ,

Do you know about registerobject in smarty 3?

Regards,
Binal

**Comment by JonisoftGermany** [comment]
Yes and no. I use the method assign() for using variables, arrays and objects in my templates.

**Comment by JonisoftGermany** [comment]
SmartyML 2.0 is a full rewrite for Smarty 3/Smarty 4. This issue is implemented and will be closed.
